### ISSUE TITLE
wifi email issue

### ISSUE THREAD

**Issue by birkenkrahe** [diva/diva-distribution#4]
i'm almost reluctant to ask this simple question here, but...well. in the WIFI.txt file, you explain that" Wifi sends mail via Gmail's SMTP secure server."  - i run a ubuntu 10.04 server from home on a pc that sits on a lan. all is good with OpenSim including access from the internet. but i don't know what is the minimal setup to get Wifi to send email (apart from the certificate imports which i did).

thanks very much! great distro! love it! /marcus

**Comment by rob-lindman** [comment]
Diva, thanks for your efforts. I am using the most recent distribution r25084 and have completed the setup. I provided gmail credentials. When sending mail, I receive a nice big yellow exception. 'Exception on sending mail to myexample@validdomain.com', 'An invalid character was found in the mail header '@'. Any idea on what to do here?
